/**
 * Convert SVG paths to Three.js ExtrudeGeometry using SVGLoader.
 *
 * Hole detection strategy:
 *
 *   For blob paths (the organic rounded shapes produced by the blob engine),
 *   we combine all paths for a layer as subpaths of a single compound SVG
 *   `<path>` with `fill-rule="evenodd"` and let SVGLoader's built-in
 *   scanline-based hole detection classify outer/inner paths natively.
 *   This correctly handles non-convex holes such as the large U-shaped inner
 *   voids that appear in complex layers, without relying on our ray-cast
 *   `createPathGroups` which can misclassify concave holes.
 *
 *   For cutout circles (laser-cutter hole circles, always CCW, small fixed
 *   radius), we find which outer Three.js shape contains each cutout's center
 *   (ray-cast in Three.js space) and add it as an additional hole.
 *
 * Multiple disconnected outer shapes on the same layer are each extruded
 * separately and then merged into a single BufferGeometry.
 */

import * as THREE from "three"
import { SVGLoader } from "three/examples/jsm/loaders/SVGLoader.js"
import { mergeGeometries } from "three/examples/jsm/utils/BufferGeometryUtils.js"
import { extractPathsFromSvg } from "@/lib/export/pathUtils"

export interface SvgToShapesOptions {
  offsetX?: number
  offsetY?: number
}

function getSvgDimensions(svgContent: string): { width: number; height: number } {
  const viewBoxMatch = svgContent.match(/viewBox="([^"]+)"/)
  if (viewBoxMatch) {
    const parts = viewBoxMatch[1].trim().split(/[\s,]+/)
    if (parts.length === 4) {
      return { width: parseFloat(parts[2]), height: parseFloat(parts[3]) }
    }
  }
  const widthMatch = svgContent.match(/width="([^"]+)"/)
  const heightMatch = svgContent.match(/height="([^"]+)"/)
  return {
    width: widthMatch ? parseFloat(widthMatch[1]) : 100,
    height: heightMatch ? parseFloat(heightMatch[1]) : 100,
  }
}

/**
 * Flip all Y coordinates of a shape/path relative to `height` (SVG→Three.js coord).
 * Uses getPoints(divisions) for a smooth approximation of arc segments.
 *
 * `divisions` is scaled by edge count so complex shapes get enough resolution.
 */
function flipShapeY(shape: THREE.Shape | THREE.Path, height: number, divisions = 128): THREE.Shape {
  const flipped = new THREE.Shape()
  const points = shape.getPoints(divisions)
  if (points.length === 0) return flipped
  flipped.moveTo(points[0].x, height - points[0].y)
  for (let i = 1; i < points.length; i++) {
    flipped.lineTo(points[i].x, height - points[i].y)
  }
  return flipped
}

/**
 * Reverse the winding order of a shape.
 * Required for outer contours after SVG→Three.js Y-flip so that ExtrudeGeometry
 * treats them as solid filled regions.
 */
function reverseWinding(shape: THREE.Shape, divisions = 128): THREE.Shape {
  const reversed = new THREE.Shape()
  const points = shape.getPoints(divisions)
  if (points.length === 0) return reversed
  reversed.moveTo(points[points.length - 1].x, points[points.length - 1].y)
  for (let i = points.length - 2; i >= 0; i--) {
    reversed.lineTo(points[i].x, points[i].y)
  }
  return reversed
}

/**
 * Parse a single SVG path d-string into a THREE.Shape via SVGLoader.
 * Returns null if the path cannot be parsed.
 */
function dStringToThreeShape(d: string, loader: SVGLoader): THREE.Shape | null {
  const miniSvg = `<svg xmlns="http://www.w3.org/2000/svg"><path d="${d}"/></svg>`
  const data = loader.parse(miniSvg)
  if (data.paths.length === 0) return null
  const shapes = SVGLoader.createShapes(data.paths[0])
  return shapes.length > 0 ? shapes[0] : null
}

/**
 * Heuristic: is this path a cutout circle?
 *
 * Cutout circles are generated by SvgPathRenderer as two half-arc commands
 * with explicit non-standard radii (diameterMm / 2 / mmPerUnit). They are
 * distinct from blob arcs which always use radius 0.5. We detect them by
 * checking that the path is short (2 arcs + M/Z) and the arc radius is ≠ 0.5.
 */
function isCutoutCircle(d: string): boolean {
  // Cutout circles look like: "M cx+r cy A r r 0 0 0 cx-r cy A r r 0 0 0 cx+r cy Z"
  // They have exactly 2 arc commands and the radius ≠ 0.5
  const arcMatches = d.match(/A\s+([\d.]+)\s+[\d.]+/g)
  if (!arcMatches || arcMatches.length !== 2) return false
  const r = parseFloat(arcMatches[0].split(/\s+/)[1])
  // Blob arcs always use r=0.5; cutout circles use a different radius
  return Math.abs(r - 0.5) > 0.01
}

/**
 * Apply optional XY offset to a shape and all its holes.
 */
function applyOffset(shape: THREE.Shape, offsetX: number, offsetY: number): THREE.Shape {
  if (offsetX === 0 && offsetY === 0) return shape
  const translated = new THREE.Shape()
  const pts = shape.getPoints(128)
  if (pts.length === 0) return shape
  translated.moveTo(pts[0].x - offsetX, pts[0].y - offsetY)
  for (let i = 1; i < pts.length; i++) {
    translated.lineTo(pts[i].x - offsetX, pts[i].y - offsetY)
  }
  translated.holes = shape.holes.map((h) => {
    const th = new THREE.Shape()
    const hp = h.getPoints(128)
    th.moveTo(hp[0].x - offsetX, hp[0].y - offsetY)
    for (let i = 1; i < hp.length; i++) {
      th.lineTo(hp[i].x - offsetX, hp[i].y - offsetY)
    }
    return th
  })
  return translated
}

/**
 * Even-odd ray-cast point-in-polygon for Three.js Vector2 polygons.
 */
function pointInPolygon2D(px: number, py: number, polygon: THREE.Vector2[]): boolean {
  let inside = false
  const n = polygon.length
  for (let i = 0, j = n - 1; i < n; j = i++) {
    const xi = polygon[i].x, yi = polygon[i].y
    const xj = polygon[j].x, yj = polygon[j].y
    if ((yi > py) !== (yj > py) && px < ((xj - xi) * (py - yi)) / (yj - yi) + xi) {
      inside = !inside
    }
  }
  return inside
}

/**
 * Convert SVG content into a merged Three.js BufferGeometry.
 *
 * Strategy:
 *  1. Separate blob paths from cutout circles.
 *  2. Combine blob paths into a single compound `<path fill-rule="evenodd">`
 *     and let SVGLoader classify outer/hole subpaths via scanline detection.
 *  3. Y-flip + winding-fix each outer shape; Y-flip its holes (already correct
 *     winding after the flip because evenodd assigns them as holes internally).
 *  4. Cutout circles are always holes — find which outer shape contains each
 *     added via ray-cast containment in Three.js space.
 *  5. Extrude each outer shape and merge.
 *
 * Returns null if no valid geometry can be produced.
 */
export function createExtrudeGeometryFromSvg(
  svgContent: string,
  options: SvgToShapesOptions = {},
  depth: number = 1,
): THREE.BufferGeometry | null {
  const { offsetX = 0, offsetY = 0 } = options
  const { height: svgHeight } = getSvgDimensions(svgContent)

  const allDs = extractPathsFromSvg(svgContent)
  if (allDs.length === 0) return null

  // Separate blob paths from cutout circles
  const blobDs = allDs.filter((d) => !isCutoutCircle(d))
  const cutoutDs = allDs.filter((d) => isCutoutCircle(d))

  if (blobDs.length === 0) return null

  const loader = new SVGLoader()

  // ── Build a single compound SVG path from all blob paths ──────────────────
  // Each blob path d-string is a closed subpath (M ... Z). Concatenating them
  // as subpaths of one <path fill-rule="evenodd"> lets SVGLoader's built-in
  // scanline hole-detection classify outer vs. inner correctly, even for
  // non-convex holes.
  const compoundD = blobDs.join(" ")
  const compoundSvg = `<svg xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="${compoundD}"/></svg>`
  const parsed = loader.parse(compoundSvg)

  if (parsed.paths.length === 0) return null

  // createShapes returns one THREE.Shape per outer contour, with holes embedded
  const svgShapes = SVGLoader.createShapes(parsed.paths[0])
  if (svgShapes.length === 0) return null

  // ── Y-flip + winding fix ──────────────────────────────────────────────────
  // SVG is y-down; Three.js is y-up. After flipShapeY:
  //   - A CW outer contour (in SVG space) becomes CCW in Three.js space.
  //     Three.js ExtrudeGeometry expects outer contours to be CW in y-up space
  //     (same as SVG's CW in y-down space = earcut "exterior" = reverseWinding).
  //   - Holes are already interior by SVGLoader classification; after flipShapeY
  //     they have the correct winding for earcut holes.
  const threeShapes: THREE.Shape[] = svgShapes.map((svgShape) => {
    let outer = flipShapeY(svgShape, svgHeight)
    outer = reverseWinding(outer)

    outer.holes = svgShape.holes.map((hole) => flipShapeY(hole, svgHeight))
    return outer
  })

  // ── Add cutout circles as holes ───────────────────────────────────────────
  // Cutout circles are small laser-cutter holes. Find which outer shape each
  // cutout belongs to by checking point containment, then add it as a hole.
  // Since threeShapes are already Y-flipped (Three.js y-up coords), we test
  // containment in Three.js space.
  if (cutoutDs.length > 0) {
    for (const cutoutD of cutoutDs) {
      const cutoutShape = dStringToThreeShape(cutoutD, loader)
      if (!cutoutShape) continue

      // Approximate cutout center in SVG y-down coords
      const cpts = cutoutShape.getPoints(8)
      if (cpts.length === 0) continue
      const svgCx = cpts.reduce((s, p) => s + p.x, 0) / cpts.length
      const svgCy = cpts.reduce((s, p) => s + p.y, 0) / cpts.length
      // Y-flip to Three.js space
      const threeCx = svgCx
      const threeCy = svgHeight - svgCy

      // Find the outer THREE.js shape that contains this center point.
      // Use a simple even-odd ray-cast on the shape's sampled points.
      let targetShape: THREE.Shape | null = null
      for (const s of threeShapes) {
        const poly = s.getPoints(128)
        if (pointInPolygon2D(threeCx, threeCy, poly)) {
          targetShape = s
          break
        }
      }
      // Fallback to first shape if ray-cast fails (e.g. point on edge)
      if (!targetShape && threeShapes.length > 0) {
        targetShape = threeShapes[0]
      }

      if (targetShape) {
        const cutoutFlipped = flipShapeY(cutoutShape, svgHeight)
        targetShape.holes.push(cutoutFlipped)
      }
    }
  }

  // ── Apply XY offset + extrude ─────────────────────────────────────────────
  const geometries: THREE.BufferGeometry[] = []

  for (let shape of threeShapes) {
    shape = applyOffset(shape, offsetX, offsetY)
    const extruded = new THREE.ExtrudeGeometry(shape, {
      depth,
      bevelEnabled: false,
    })
    geometries.push(extruded)
  }

  if (geometries.length === 0) return null
  if (geometries.length === 1) return geometries[0]

  // Merge multiple disconnected shapes (e.g. two donuts on the same layer)
  const merged = mergeGeometries(geometries, false)
  // Dispose individual geometries since they're merged
  for (const g of geometries) g.dispose()
  return merged
}
